heroku container:push web --arg SPOTIFY_ID=${SPOTIFY_ID},SPOTIFY_SECRET=${SPOTIFY_SECRET},SLACK_CLIENT_ID=${SLACK_CLIENT_ID},SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET},SLACK_TOKEN=${SLACK_TOKEN},SPOTIFY_REDIRECT_URL=${SPOTIFY_REDIRECT_URL},NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME},NEW_RELIC_LICENSE=${NEW_RELIC_LICENSE}

heroku container:release web