FROM golang:1.18-alpine

ARG SPOTIFY_SLACK_APP_SLACK_CLIENT_ID
ARG SPOTIFY_SLACK_APP_SLACK_CLIENT_SECRET
ARG SPOTIFY_SLACK_APP_SPOTIFY_REDIRECT_URL
ARG SPOTIFY_SLACK_APP_NEW_RELIC_APP_NAME
ARG SPOTIFY_SLACK_APP_NEW_RELIC_LICENSE
ARG SPOTIFY_SLACK_APP_DATABASE_URL
ARG SPOTIFY_SLACK_APP_SLACK_AUTH_URL

ENV SPOTIFY_SLACK_APP_SLACK_CLIENT_ID ${SPOTIFY_SLACK_APP_SLACK_CLIENT_ID}
ENV SPOTIFY_SLACK_APP_SLACK_CLIENT_SECRET ${SPOTIFY_SLACK_APP_SLACK_CLIENT_SECRET}
ENV SPOTIFY_SLACK_APP_SPOTIFY_REDIRECT_URL ${SPOTIFY_SLACK_APP_SPOTIFY_REDIRECT_URL}
ENV SPOTIFY_SLACK_APP_NEW_RELIC_APP_NAME ${SPOTIFY_SLACK_APP_NEW_RELIC_APP_NAME}
ENV SPOTIFY_SLACK_APP_NEW_RELIC_LICENSE ${SPOTIFY_SLACK_APP_NEW_RELIC_LICENSE}
ENV SPOTIFY_SLACK_APP_DATABASE_URL ${SPOTIFY_SLACK_APP_DATABASE_URL}
ENV SPOTIFY_SLACK_APP_SLACK_AUTH_URL ${SPOTIFY_SLACK_APP_SLACK_AUTH_URL}
ENV SPOTIFY_SLACK_APP_PORT 8080

ADD . /app

WORKDIR /app

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/spotify-status ./src

RUN chmod +x ./bin/spotify-status

EXPOSE 8080

CMD ["./bin/spotify-status"]
