FROM golang:latest

ARG SPOTIFY_ID
ARG SPOTIFY_SECRET
ARG SLACK_CLIENT_ID
ARG SLACK_CLIENT_SECRET
ARG SLACK_TOKEN
ARG SPOTIFY_REDIRECT_URL
ARG NEW_RELIC_APP_NAME
ARG NEW_RELIC_LICENSE

ENV SPOTIFY_ID ${SPOTIFY_ID}
ENV SPOTIFY_SECRET ${SPOTIFY_SECRET}
ENV SLACK_CLIENT_ID ${SLACK_CLIENT_ID}
ENV SLACK_CLIENT_SECRET ${SLACK_CLIENT_SECRET}
ENV SLACK_TOKEN ${SLACK_TOKEN}
ENV SPOTIFY_REDIRECT_URL ${SPOTIFY_REDIRECT_URL}
ENV NEW_RELIC_APP_NAME ${NEW_RELIC_APP_NAME}
ENV NEW_RELIC_LICENSE ${NEW_RELIC_LICENSE}
ENV PORT 8080

ADD . /app

WORKDIR /app

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/spotify-status

RUN chmod +x ./bin/spotify-status

EXPOSE 8080

EXPOSE $PORT

CMD ["./bin/spotify-status"]